storeItemList:
  - id: '16373231677670.5036328199004867'
    name: selectedApartment
    value: {}
    valueType: object
    initialValue: {}
    version: 0
metadata:
  favicon: ''
  code: "<style>\n  .apartment nb-card {\n  \tcursor: pointer;\n  }\n  \n  .apartment nb-card:hover {\n  \tbackground-color: #E8EEFB;\n  }\n  \n  .ellipsis h2, .ellipsis p {\n    white-space: nowrap;\n    overflow: hidden;\n    text-overflow: ellipsis;\n    display: block!important;\n  }\n  .ellipsis h2 {\n    line-height: 24px;\n  }\n  \n  ub-horizontal-menu a[nbButton].active, ub-horizontal-menu a[nbButton]:hover {\n    background-color: rgb(69 112 246 / 37%)!important;\n  }\n  \n  .no-shadow button {\n    filter: none!important;\n  }\n</style>"
  title: '[MOCK DB] Booking'
  description: ''
  breakpoints: []
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 2
  density: compact
internalType: project
